In [1]:
#province: Drenthe
#crop: maize(green)
#year: 2022-04-01 to 2022-11-21
#This notebook retrives meteological data from KNMI GRIB files, based on the coordinates of plots in Drenthe
# and save them as CSV files that can be used in WOFOST ensenmble simulation

#### Processing meteorological data

In [1]:
import warnings
warnings.filterwarnings("ignore", message="GRIB: .*", category=RuntimeWarning)
#ignore the warnings

In [6]:
import fpcup
fpcup.test()

Succesfully imported fpcup version 0.0.1 from C:\Users\Suliko\q34\25q3\thesis\fpcup_new\fpcup-main\fpcup\__init__.py.

In [7]:
# Setup
year = 2022
brp = fpcup.io.load_brp(year)
crop_species = "barley"
province = fpcup.geo.process_input_province("Drenthe")
brp_plots = fpcup.io.query_brp(brp, province=province, crop_species=crop_species)
brp_plots #brp plots in Drenthe. totally 5048 plots

,crop,crop_code,province,area,crop_species,latitude,longitude,geometry
65,barley (spring),236,DR,4.754415,barley,52.796016,6.882431,"POLYGON ((256042.323 535285.836, 256044.359 53..."
84,barley (spring),236,DR,11.200659,barley,52.838428,7.054879,"POLYGON ((266920.198 539976.979, 266925.857 53..."
171,barley (spring),236,DR,1.531765,barley,52.904292,6.910060,"POLYGON ((257340.124 547303.167, 257456.747 54..."
172,barley (spring),236,DR,8.576494,barley,52.885230,6.908263,"POLYGON ((257535.836 545555.834, 257536.419 54..."
220,barley (spring),236,DR,2.549430,barley,52.994562,6.688762,"POLYGON ((242268.705 557104.411, 242269.857 55..."
...,...,...,...,...,...,...,...,...
114164,barley (spring),236,DR,2.004656,barley,52.918369,6.718633,"POLYGON ((244495.703 548845.750, 244496.536 54..."
114165,barley (spring),236,DR,2.511491,barley,52.902910,6.708485,"POLYGON ((243903.089 546923.516, 243911.896 54..."
114295,barley (spring),236,DR,1.027462,barley,52.729927,6.279449,"POLYGON ((215314.218 527206.864, 215322.040 52..."
114359,barley (spring),236,DR,3.978249,barley,52.990446,6.773184,"POLYGON ((248163.568 556814.638, 248205.670 55..."
114461,barley (winter),235,DR,4.948594,barley,52.762560,6.719325,"POLYGON ((244814.967 531264.157, 244870.579 53..."

In [8]:
brp_barley = brp_plots[brp_plots["crop"] == "barley (winter)"]

In [9]:
brp_barley

,crop,crop_code,province,area,crop_species,latitude,longitude,geometry
268,barley (winter),235,DR,2.377218,barley,52.767790,6.725163,"POLYGON ((245187.638 531901.405, 245196.599 53..."
269,barley (winter),235,DR,1.871636,barley,52.768060,6.723638,"POLYGON ((245132.106 532019.383, 245157.763 53..."
270,barley (winter),235,DR,1.006191,barley,52.767717,6.726866,"POLYGON ((245440.184 531946.746, 245459.024 53..."
415,barley (winter),235,DR,20.157236,barley,52.790621,7.026853,"POLYGON ((265497.294 534387.683, 265588.354 53..."
482,barley (winter),235,DR,1.389190,barley,53.056825,6.792444,"POLYGON ((249177.447 564158.556, 249190.753 56..."
...,...,...,...,...,...,...,...,...
105248,barley (winter),235,DR,6.023288,barley,52.914757,7.023529,"POLYGON ((264980.027 548423.010, 265197.541 54..."
108603,barley (winter),235,DR,31.670920,barley,53.085299,6.774683,"POLYGON ((247522.532 567037.074, 247988.880 56..."
110271,barley (winter),235,DR,0.519363,barley,52.884238,6.933128,"POLYGON ((259056.187 545185.618, 259094.913 54..."
113503,barley (winter),235,DR,7.016160,barley,53.067764,6.781902,"POLYGON ((248189.037 565159.076, 248787.382 56..."
114461,barley (winter),235,DR,4.948594,barley,52.762560,6.719325,"POLYGON ((244814.967 531264.157, 244870.579 53..."

In [4]:
# brp_maize = brp_plots[brp_plots["crop"] == "maize (green)"]
# brp_maize

,crop,crop_code,province,area,crop_species,latitude,longitude,geometry
49,maize (green),259,DR,1.243862,maize,52.850283,6.525109,"POLYGON ((231720.880 540878.997, 231722.464 54..."
115,maize (green),259,DR,1.343735,maize,52.755400,6.302030,"POLYGON ((216804.125 530038.974, 216834.772 53..."
167,maize (green),259,DR,1.843291,maize,52.750754,6.181471,"POLYGON ((208656.394 529414.356, 208656.468 52..."
244,maize (green),259,DR,4.483355,maize,52.640474,6.954269,"POLYGON ((260992.390 517990.224, 261004.033 51..."
267,maize (green),259,DR,3.204383,maize,52.745783,6.647185,"POLYGON ((240243.978 529491.285, 240119.716 52..."
...,...,...,...,...,...,...,...,...
114356,maize (green),259,DR,1.821246,maize,53.015989,6.771591,"POLYGON ((247868.777 559588.500, 247879.271 55..."
114387,maize (green),259,DR,1.424741,maize,52.765242,6.929387,"POLYGON ((259105.758 531895.085, 259106.757 53..."
114388,maize (green),259,DR,3.032424,maize,52.737648,6.864302,"POLYGON ((254856.922 528670.152, 254856.381 52..."
114403,maize (green),259,DR,3.177108,maize,52.727277,6.282217,"POLYGON ((215540.832 526823.264, 215602.890 52..."
114425,maize (green),259,DR,10.120581,maize,52.890265,6.632227,"POLYGON ((238700.044 545271.294, 238700.816 54..."

In [ ]:
#too many points, take too much time to compute
#employe k-means to reduce the number of points

In [6]:
from sklearn.cluster import KMeans

X = brp_barley[["latitude", "longitude"]]
brp_barley["cluster"] = KMeans(n_clusters=50, random_state=42).fit_predict(X)

sampled = brp_barley.groupby("cluster").apply(lambda x: x.sample(1)).reset_index(drop=True)

In [7]:
sampled.to_csv("./sampled_points_barley_spring.csv", index=False)

In [10]:
brp_barley.to_csv("./barley_points.csv", index=False)

In [3]:
from osgeo import gdal
import numpy as np

In [4]:
#inspect the grib file
def inspect_rh_by_band(fpath, rh_band=27):
    ds = gdal.Open(fpath, gdal.GA_ReadOnly)
    if ds is None:
        raise FileNotFoundError(f"Cannot open: {fpath}")
    print("RasterCount:", ds.RasterCount)

    if rh_band > ds.RasterCount:
        raise IndexError(f"Band {rh_band} > RasterCount {ds.RasterCount}")

    b = ds.GetRasterBand(rh_band)
    md = b.GetMetadata()  
    print("Band:", rh_band)
    print("Description:", b.GetDescription())
    print("GRIB_ELEMENT:", md.get("GRIB_ELEMENT"))
    print("GRIB_COMMENT:", md.get("GRIB_COMMENT"))
    print("GRIB_UNIT:", md.get("GRIB_UNIT"))
    print("GRIB_VALID_TIME:", md.get("GRIB_VALID_TIME"))
    print("GRIB_REF_TIME:", md.get("GRIB_REF_TIME"))

    arr = b.ReadAsArray().astype("float32")
    nodata = b.GetNoDataValue()
    if nodata is not None:
        arr[arr == nodata] = np.nan

    print("RH stats [%]: min=", np.nanmin(arr), "max=", np.nanmax(arr), "mean=", np.nanmean(arr))

inspect_rh_by_band(r"E:/dataset_month1/HA43_N20_202109010000_00000_GB", rh_band=27)

RasterCount: 46
Band: 27
Description: 2[m] HTGL (Specified height level above ground)
GRIB_ELEMENT: RH
GRIB_COMMENT: Relative humidity [%]
GRIB_UNIT: [%]
GRIB_VALID_TIME: 1630454400
GRIB_REF_TIME: 1630454400
RH stats [%]: min= 0.65746284 max= 0.99999976 mean= 0.8568832

In [ ]:
# process the data and save as csv 
!python C:/users/suliko/q34/25q3/thesis/fpcup_new/fpcup-main/Mygetmeteodata.py